server:
  port: 8082
spring:
  rabbitmq:
    host: 124.221.169.240
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 100
        acknowledge-mode: manual
  redis:
    host: 124.221.169.240
    port: 6379
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: GEVYEIGPSHKSBFFF
    username: junlogz@163.com
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
        debug: true