spring:
  rabbitmq:
    host: 124.221.169.240
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    # 打开消息确认机制
    publisher-confirms: true
    # 打开消息返回
    publisher-returns: true
    template:
      mandatory: true